# Generated by Django 4.2.5 on 2023-10-26 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_alter_taskitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
