# Generated by Django 4.2.5 on 2023-10-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0004_taskitem_coloritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'To-do'), (1, 'Do-today'), (2, 'In-progress'), (3, 'Done')], default=0),
        ),
    ]
