# Generated by Django 4.2.5 on 2023-10-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0005_alter_taskitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskitem',
            old_name='colorItem',
            new_name='color',
        ),
    ]
