# Generated by Django 4.2.5 on 2023-10-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
