# Generated by Django 4.2.5 on 2023-12-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0011_taskitem_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
