# Generated by Django 4.2.5 on 2024-01-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0013_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='color',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasklist.member'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborated_tasks', to='tasklist.member'),
        ),
    ]
