# Generated by Django 4.2.5 on 2024-01-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0014_member_color_member_email_member_initials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasklist.member'),
        ),
    ]
