# Generated by Django 4.2.5 on 2024-01-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0015_alter_taskitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='collaborator',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborated_tasks', to='tasklist.member'),
        ),
    ]
