# Generated by Django 4.2.5 on 2024-01-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0019_regist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regist',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='color',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='regist',
            name='last_name',
        ),
    ]
