# Generated by Django 4.2.5 on 2024-01-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0020_rename_first_name_regist_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regist',
        ),
    ]
