# Generated by Django 4.2.5 on 2024-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0022_regist'),
    ]

    operations = [
        migrations.AddField(
            model_name='regist',
            name='color',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regist',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
