# Generated by Django 4.2.5 on 2024-01-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0023_regist_color_regist_initials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regist',
        ),
    ]
