# Generated by Django 4.2.5 on 2024-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0024_delete_regist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('initials', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
