# Generated by Django 4.2.5 on 2024-01-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0026_alter_regist_options_alter_regist_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regist',
        ),
    ]
