# Generated by Django 4.2.5 on 2024-01-10 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasklist', '0029_alter_taskitem_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='collaborator',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborated_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
