# Generated by Django 4.2.5 on 2024-01-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0031_alter_taskitem_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='color',
            field=models.SmallIntegerField(choices=[(60, 'Yellow'), (240, 'Blue'), (120, 'Green'), (30, 'Orange'), (0, 'Red'), (180, 'Cyan'), (300, 'Purple')], default=60),
        ),
    ]
