# Generated by Django 4.2.5 on 2024-01-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0032_alter_taskitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='color',
            field=models.SmallIntegerField(choices=[(0, 'Yellow'), (1, 'Blue'), (2, 'Green'), (3, 'Orange'), (4, 'Red'), (5, 'Cyan'), (6, 'Purple')], default=0),
        ),
    ]
